name: 'Terraform Module Tests'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    name: 'Terraform Integration'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.7

      - name: Terraform fmt
        id: fmt
        run: terraform fmt
        continue-on-error: true
      
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.3

      - name: 'Run Terratest integration_test'
        run: go test -v -timeout 30m --tags integration_test ./...
        working-directory: tests/
